title: Ethan Benton Portfolio
job_titles: System Administrator | DevOps | Generative AI
location: Chesapeake, VA
mobile_number: (757) 803-1913
email: mailto:ethanfbenton@gmail.com
github_url: "https://bigewoo.github.io"
linkedin_url: "https://www.linkedin.com/in/ethan-benton-a08a14313/"